name: Build and Release

on:
  push:
    tags:
      - r*
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release-Tag (z. B. v1.2.3)'
        required: true
        type: string

jobs:
  call-reusable:
    uses: mjbohn/GithubWorkflows/.github/workflows/dotnet-build-and-release-win.yml@main
    with:
      tag: ${{ inputs.tag }}
      project_path: 'CPU_emu'
      zip_name: 'sim6502.zip'
      configuration: 'Release'
